// <auto-generated />
using System;
using Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SubastaDbContext))]
    [Migration("20250624173921_InitialCreate8")]
    partial class InitialCreate8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Models.PostgreSQL.HistorialSubastasPostgreSQL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSubasta")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoFinal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SubastaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubastaId");

                    b.ToTable("HistorialSubasta");
                });

            modelBuilder.Entity("Infrastructure.Models.PostgreSQL.SubastaPostgreSQL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("idProducto")
                        .HasColumnType("uuid");

                    b.Property<decimal>("incrementoMinimo")
                        .HasColumnType("numeric");

                    b.Property<decimal>("precioReserva")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Subasta");
                });

            modelBuilder.Entity("Infrastructure.Models.PostgreSQL.HistorialSubastasPostgreSQL", b =>
                {
                    b.HasOne("Infrastructure.Models.PostgreSQL.SubastaPostgreSQL", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subasta");
                });
#pragma warning restore 612, 618
        }
    }
}
